# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EarthData Covid19
email: info@earthdata.ch
description: >- # this means to ignore newlines until "baseurl:"
  Kritische Informationen rund um das Thema Covid19, Recht und Gesundheit
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://covid19.earthdata.ch" # the base hostname & protocol for your site, e.g. http://example.com
minima:
  skin: classic
  
author:
  name: "Joerg Roth"
  email: "info@earthdata.ch"

header_pages:
  - blog/index.html
  - files.md
  - org.md
  - person.md
  - media.md

icons:
  globe:    '<i class="fas fa-globe" style="color: #008800"></i>'
  facebook: '<i class="fab fa-facebook" style="color: #3B5998;"></i>'
  youtube:  '<i class="fab fa-youtube" style="color: #FF0000;"></i>'
  telegram: '<i class="fab fa-telegram" style="color: #0088CC;"></i>'
  forward:  '<i class="fa fa-forward" style="color: black;"></i>'
  movie:    '<i class="fas fa-film" style="color: black;"></i>' 
  github:   '<i class="fab fa-github" style="color: black;"></i>' 
  twitter:  '<i class="fab fa-twitter" style="color: #55ACEE;"></i>' 

paginate: 8
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
remote_theme: https://github.com/jekyll/minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
